################################################################################
#   Section: Organizations
################################################################################
Organizations:
    - &OrdererOrg
        Name: Orderer
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/kshrd.com.kh/msp


    - &PeerOrg
        Name: Org1MSP
        ID: Org1MSP
        MSPDir: crypto-config/peerOrganizations/org1.kshrd.com.kh/msp
        AnchorPeers:
            - Host: peer0.org1.kshrd.com.kh
              Port: 7051

###############################################################################
#   SECTION: Capabilities
################################################################################
Capabilities:
    Global: &ChannelCapabilities
        V1_1: true
    Orderer: &OrdererCapabilities
        V1_1: true
    Application: &ApplicationCapabilities
        V1_2: true

################################################################################
#   SECTION: Application
################################################################################
Application: &ApplicationDefaults
    Organizations:

################################################################################
#   SECTION: Orderer
################################################################################
Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - orderer.kshrd.com.kh:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Kafka:
        Brokers:
            - kafka1:9092
            - kafka2:9092
            - kafka3:9092
    Organizations:

################################################################################
#   Profile
################################################################################
Profiles:
    TestGenesis:
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            OrdererType: solo
            Addresses:
                - orderer.kshrd.com.kh:7050
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            TestConsortium:
                Organizations:
                    - *PeerOrg

    TestChannel:
        Consortium: TestConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *PeerOrg
            Capabilities:
                <<: *ApplicationCapabilities
